name: Reusable Workflow
on: 
  workflow_dispatch:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name : test app
          #uses: {owner}/{repo}/.github/workflows/{myreusable-workflow.yaml}@main #remote
          uses: ./.github/workflows/ex3-reusable.yml #local
          with:
            node-version: 14
